import React from 'react'

export const Sponsors = {
    "Adams":"adams.jpg",
    "Alsco":"alsco.jpg",
    "Brent Lucas Builders":"brentlucasbuilders.png",
    "Build Me Dunedin Limited":"buildme.jpg",
    "Cableways":"cableways.png",
    "Cartridge World Dunedin":"cartridgeworld.jpg",
    "Chipmunks Playland":"chipmunks.png",
    "Custom Signs":"customsigns.jpg",
    "Cutlers":"cutlers.jpg",
    "Davies Heat n Cool":"davies.png",
    "DG Flooring Ltd":"dg.png",
    "Edinburgh Realty":"edinburgh.jpg",
    "Filadelfio's Dunedin Gardens":"filidelfios.jpg",
    "Flooring Xtra":"flooringxtra.png",
    "Graham Glover Brick layer":"grahamglover.png",
    "House of Travel":"houseoftravel.jpg",
    "John Swans":"johnswan.png",
    "Justin Bell Flooring":"justinbell.png",
    "K.J Mac Contracting LTD":"kjmac.jpg",
    "Lion Nathan":"lionnathan.png",
    "Mac's Contracting":"macs.jpg",
    "Malt House Brewing Supplies":"malthouse.jpg",
    "MG3 Apparel":"mg3.png",
    "Mike Shanks Hair Design":"mikeshanks.png",
    "Mike Teasdale Motors":"miketeasdalemotors.png",
    "Mitre 10 Mega":"mitre10.png",
    "Moore Markhams":"mooremarkhams.png",
    "Mornington Tavern":"mornington.png",
    "Otago Engineering":"otagoengineering.png",
    "Property Brokers":"propertybrokers.png",
    "Resolve IT":"resolveit.jpg",
    "Roslyn Pharmacy":"roslynpharmacy.jpg",
    "Roslyn Physio":"roslynphysio.png",
    "RSM Contracting":"rsm.png",
    "S L Parker":"slparker.jpg",
    "Salmac":"salmac.png",
    "Scaffold for Less":"scaffoldforless.png",
    "Stonewood Homes":"stonewood.png",
    "Subway Kaikorai Valley":"subway.jpg",
    "Summerset Bishopscourt":"summerset.jpg",
    "Switchbuild":"switchbuild.png",
    };
    