export const Sponsors = [
  { label: "Adams", value: "adams.jpg", h: 180, w: 1200 },
  { label: "Alsco", value: "alsco.jpg", h: 180, w: 1200 },
  {
    label: "Brent Lucas Builders",
    value: "brentlucasbuilders.png",
    h: 200,
    w: 725,
  },
  { label: "Build Me Dunedin Limited", value: "buildme.jpg", h: 180, w: 1200 },
  { label: "Cableways", value: "cableways.png", h: 191, w: 270 },
  {
    label: "Cartridge World Dunedin",
    value: "cartridgeworld.jpg",
    h: 180,
    w: 1200,
  },
  { label: "Chipmunks Playland", value: "chipmunks.png", h: 130, w: 386 },
  { label: "Custom Signs", value: "customsigns.jpg", h: 180, w: 1200 },
  { label: "Cutlers", value: "cutlers.bmp", h: 135, w: 374 },
  { label: "Davies Heat n Cool", value: "davies.png", h: 78, w: 220 },
  { label: "DG Flooring Ltd", value: "dg.png", h: 537, w: 790 },
  { label: "Edinburgh Realty", value: "edinburgh.jpg", h: 123, w: 409 },
  {
    label: "Filadelfios Dunedin Gardens",
    value: "filedelfios.jpg",
    h: 180,
    w: 1200,
  },
  { label: "Flooring Xtra", value: "flooringxtra.png", h: 101, w: 499 },
  {
    label: "Graham Glover Brick layer",
    value: "grahamglover.png",
    h: 88,
    w: 551,
  },
  { label: "House of Travel", value: "houseoftravel.jpg", h: 370, w: 2368 },
  { label: "John Swans", value: "johnswan.png", h: 65, w: 191 },
  { label: "Justin Bell Flooring", value: "justinbell.png", h: 174, w: 485 },
  { label: "K.J Mac Contracting LTD", value: "kjmac.jpg", h: 180, w: 1200 },
  { label: "Lion Nathan", value: "lionnathan.png", h: 337, w: 565 },
  { label: "Macs Contracting", value: "macs.jpg", h: 371, w: 2369 },
  {
    label: "Malt House Brewing Supplies",
    value: "malthouse.jpg",
    h: 180,
    w: 1200,
  },
  { label: "MG3 Apparel", value: "mg3.png", h: 191, w: 450 },
  { label: "Mike Shanks Hair Design", value: "mikeshanks.png", h: 123, w: 393 },
  {
    label: "Mike Teasdale Motors",
    value: "miketeasdalemotors.png",
    h: 112,
    w: 549,
  },
  { label: "Mitre 10 Mega", value: "mitre10.png", h: 127, w: 225 },
  { label: "Moore Markhams", value: "mooremarkhams.png", h: 81, w: 529 },
  { label: "Mornington Tavern", value: "mornington.png", h: 154, w: 327 },
  { label: "Otago Engineering", value: "otagoengineering.png", h: 137, w: 328 },
  { label: "Property Brokers", value: "propertybrokers.png", h: 48, w: 283 },
  { label: "Resolve IT", value: "resolveit.jpg", h: 371, w: 2368 },
  { label: "Roslyn Pharmacy", value: "roslynpharmacy.jpg", h: 886, w: 5906 },
  { label: "Roslyn Physio", value: "roslynphysio.png", h: 119, w: 574 },
  { label: "RSM Contracting", value: "rsm.png", h: 114, w: 330 },
  { label: "S L Parker", value: "slparker.jpg", h: 180, w: 1200 },
  { label: "Salmac", value: "salmac.png", h: 77, w: 600 },
  { label: "Scaffold for Less", value: "scaffoldforless.png", h: 359, w: 451 },
  { label: "Stonewood Homes", value: "stonewood.png", h: 201, w: 1040 },
  { label: "Subway Kaikorai Valley", value: "subway.jpg", h: 180, w: 1200 },
  { label: "Summerset Bishopscourt", value: "summerset.jpg", h: 134, w: 450 },
  { label: "Switchbuild", value: "switchbuild.png", h: 99, w: 331 },
];
